### ISSUE TITLE
0.6.0 (Jewel) - Roadmap

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox-issues#368]

**Comment by pirog** [comment]
- [ ] kbox update functionality 
- [ ] better CLI metadata and user feedback
- [ ] upgrade syncthing and make more solid
- [ ] bug fixes
