### ISSUE TITLE
0.7.0 - Kelly Clarkson Roadmap

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox-issues#391]

**Comment by pirog** [comment]
- [ ] Upgrade syncthing to version 11
- [ ] Syncthing stress test
- [ ] `kbox create` command
