### ISSUE TITLE
0.8.0 Roadmap - Wrecking Ball

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox-issues#440]

**Comment by pirog** [comment]
- [ ] Clean up app.js
- [ ] General housekeeping 
- [ ] Removing pyramids of doom
- [ ] Switching over to promises where applicable
- [ ] Code audit
